---
- name: Install Python venv package
  apt:
    name: python3-venv
    state: present

- name: Create App Directory
  file:
    path: /opt/astraeus
    state: directory
    owner: vagrant
    group: vagrant

- name: Create Virtual Environment and install dependencies
  pip:
    name: 
      - uvicorn
      - fastapi
      - psycopg2-binary
    virtualenv: /opt/astraeus/venv
    virtualenv_command: /usr/bin/python3 -m venv

- name: Deploy FastAPI Application from Template
  template:
    src: main.py.j2
    dest: /opt/astraeus/main.py
    owner: vagrant
    group: vagrant
    mode: '0644'
  notify: restart astraeus

- name: Deploy Systemd service file
  template:
    src: astraeus.service.j2
    dest: /etc/systemd/system/astraeus.service
    mode: '0644'
  notify: restart astraeus